# ============================================================
# LKS Bekasi 2026 - Autograding Inventory
# node-1 = Gateway | node-2 = node1 | node-3 = node2 | node-4 = nfs
# ============================================================

[peserta_1]
gw_p1    ansible_host=172.235.251.200  peserta=1 nama="Peserta 1" role=gateway
node1_p1 ansible_host=172.235.251.251  peserta=1 nama="Peserta 1" role=node1
node2_p1 ansible_host=172.235.240.177  peserta=1 nama="Peserta 1" role=node2
nfs_p1   ansible_host=172.235.240.161  peserta=1 nama="Peserta 1" role=nfs

[peserta_2]
gw_p2    ansible_host=104.64.0.206     peserta=2 nama="Peserta 2" role=gateway
node1_p2 ansible_host=172.235.240.37   peserta=2 nama="Peserta 2" role=node1
node2_p2 ansible_host=172.235.240.72   peserta=2 nama="Peserta 2" role=node2
nfs_p2   ansible_host=172.235.240.83   peserta=2 nama="Peserta 2" role=nfs

[peserta_3]
gw_p3    ansible_host=172.235.251.224  peserta=3 nama="Peserta 3" role=gateway
node1_p3 ansible_host=172.235.240.203  peserta=3 nama="Peserta 3" role=node1
node2_p3 ansible_host=172.235.240.86   peserta=3 nama="Peserta 3" role=node2
nfs_p3   ansible_host=172.235.240.80   peserta=3 nama="Peserta 3" role=nfs

[peserta_4]
gw_p4    ansible_host=172.235.240.113  peserta=4 nama="Peserta 4" role=gateway
node1_p4 ansible_host=172.235.240.60   peserta=4 nama="Peserta 4" role=node1
node2_p4 ansible_host=172.235.240.202  peserta=4 nama="Peserta 4" role=node2
nfs_p4   ansible_host=172.235.251.174  peserta=4 nama="Peserta 4" role=nfs

[peserta_5]
gw_p5    ansible_host=104.64.0.110     peserta=5 nama="Peserta 5" role=gateway
node1_p5 ansible_host=172.232.239.147  peserta=5 nama="Peserta 5" role=node1
node2_p5 ansible_host=172.232.239.153  peserta=5 nama="Peserta 5" role=node2
nfs_p5   ansible_host=172.235.251.207  peserta=5 nama="Peserta 5" role=nfs

[peserta_6]
gw_p6    ansible_host=172.235.240.138  peserta=6 nama="Peserta 6" role=gateway
node1_p6 ansible_host=172.235.240.111  peserta=6 nama="Peserta 6" role=node1
node2_p6 ansible_host=172.235.251.98   peserta=6 nama="Peserta 6" role=node2
nfs_p6   ansible_host=172.232.239.249  peserta=6 nama="Peserta 6" role=nfs

[peserta_7]
gw_p7    ansible_host=172.235.251.204  peserta=7 nama="Peserta 7" role=gateway
node1_p7 ansible_host=172.235.240.137  peserta=7 nama="Peserta 7" role=node1
node2_p7 ansible_host=172.235.251.63   peserta=7 nama="Peserta 7" role=node2
nfs_p7   ansible_host=172.235.251.250  peserta=7 nama="Peserta 7" role=nfs

[peserta_8]
gw_p8    ansible_host=172.235.251.245  peserta=8 nama="Peserta 8" role=gateway
node1_p8 ansible_host=172.235.240.50   peserta=8 nama="Peserta 8" role=node1
node2_p8 ansible_host=172.235.240.17   peserta=8 nama="Peserta 8" role=node2
nfs_p8   ansible_host=172.235.251.230  peserta=8 nama="Peserta 8" role=nfs

[all:vars]
ansible_user=root
ansible_password=LksBekasi2026!
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
